/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.awt.CardLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author thakur-huni
 */
public class Dashboard extends javax.swing.JFrame {
    CardLayout layout;
    static Dashboard dashboard; 
    private String name;
    private String username,userType;
    
    public Dashboard(String name,String username,String userType) {
        this.name=name;
        this.username=username;
        this.userType=userType;
        setVisible(true);
       
        initComponents();
      //  setProfileName();
        //addPanels();
    }
    
    public void setProfileName()
    {
        lblUsername.setText(name);
        lblHeadText.setText(userType+" Panel");
    }
    public void addPanels(Dashboard dashboard) throws SQLException
    {
         this.dashboard=dashboard;
         layout = new CardLayout();
         pnlParent.setLayout(layout);
         pnlParent.add("First", new HomePage());
         pnlParent.add("Second", new Menus(dashboard));
         pnlParent.add("Three", new User(username,dashboard));
         pnlParent.add("Four", new AddUser(dashboard));
         pnlParent.add("Five", new AddBook(dashboard));
         pnlParent.add("Six", new AddBookCategory(dashboard));
         pnlParent.add("Seven", new IssueBook());
         pnlParent.add("Eight", new ManageUsers());
         pnlParent.add("Nine", new ManageAdmin());
         pnlParent.add("Ten", new ManageBook(dashboard));
         
         
         layout.next(pnlParent);
         layout.next(pnlParent);
         layout.show(pnlParent,"First");
    }
    
    public void addHomePage() {
        layout.show(pnlParent, "First");
        lblHeadText.setText("Admin Panel");
        setTitle("Dashboard");
    }
    public void addMenuPage() {
        layout.show(pnlParent, "Second");
        lblHeadText.setText("Admin Panel / Menus");
        setTitle("Menu");
    }
    public void addUserDetailPage() {
        layout.show(pnlParent, "Three");
        lblHeadText.setText("Admin Panel / Profile");
        setTitle("Profile");
    }
    public void addNewUserPage() {
        layout.show(pnlParent, "Four");
        lblHeadText.setText("Admin Panel / Add New User");
        setTitle("Add User");
    }
    public void addBookAddPage() {
        layout.show(pnlParent, "Five");
        lblHeadText.setText("Admin Panel / Add New Book");
        setTitle("Add Book");
    }
    public void addBookCatAddPage() {
        layout.show(pnlParent, "Six");
        lblHeadText.setText("Admin Panel / Add New Genre");
        setTitle("Manage Genre");
    }
    public void addIssueBookPage() {
        layout.show(pnlParent, "Seven");
        lblHeadText.setText("Admin Panel / Issue Book");
        setTitle("Issue Book");
    }
    public void addManageUserPage() {
        layout.show(pnlParent, "Eight");
        lblHeadText.setText("Admin Panel / Manage Users");
        setTitle("Manage Users");
    }
    public void addManageAdminPage() {
        layout.show(pnlParent, "Nine");
        lblHeadText.setText("Admin Panel / Manage Admins");
        setTitle("Manage Admins");
    }
    public void addManageBookPage() {
        layout.show(pnlParent, "Ten");
        lblHeadText.setText("Admin Panel / Manage Books");
        setTitle("Manage Books");
    }
    public void setColor(JPanel pnl)
    {
        pnl.setBackground(new Color(17,80,204));
    }
    public void resetColor(JPanel pnl)
    {
        pnl.setBackground(new Color(45,118,232));
    }
    public void logoutNow()
    {
        dispose();
        JOptionPane.showMessageDialog(this, "Logout successfull...");
         new Login();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSideMenu = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlHome = new javax.swing.JPanel();
        lblMenuName3 = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        lblMenuName5 = new javax.swing.JLabel();
        pnlHelp = new javax.swing.JPanel();
        lblMenuName6 = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        lblMenuName7 = new javax.swing.JLabel();
        pnlLogout = new javax.swing.JPanel();
        lblMenuName8 = new javax.swing.JLabel();
        pnlTop = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        lblHeadText = new javax.swing.JLabel();
        pnlUser = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lbluserimg = new javax.swing.JLabel();
        pnlParent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setBackground(new java.awt.Color(254, 254, 254));
        setMinimumSize(new java.awt.Dimension(810, 500));

        pnlSideMenu.setBackground(new java.awt.Color(45, 118, 232));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/e-lib.jpeg"))); // NOI18N
        lblLogo.setToolTipText("e-Lib Logo");

        pnlHome.setBackground(new java.awt.Color(45, 118, 232));
        pnlHome.setToolTipText("Go to Home");
        pnlHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHomeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHomeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHomeMouseEntered(evt);
            }
        });

        lblMenuName3.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        lblMenuName3.setForeground(new java.awt.Color(254, 254, 254));
        lblMenuName3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        lblMenuName3.setText("Home");
        lblMenuName3.setToolTipText("Go to Home");
        lblMenuName3.setIconTextGap(10);
        lblMenuName3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuName3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMenuName3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuName3MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenuName3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblMenuName3))
        );

        pnlMenu.setBackground(new java.awt.Color(45, 118, 232));
        pnlMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuMouseEntered(evt);
            }
        });

        lblMenuName5.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        lblMenuName5.setForeground(new java.awt.Color(254, 254, 254));
        lblMenuName5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/order.png"))); // NOI18N
        lblMenuName5.setText("Menu");
        lblMenuName5.setToolTipText("Show Menus");
        lblMenuName5.setIconTextGap(10);
        lblMenuName5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuName5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMenuName5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuName5MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblMenuName5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(lblMenuName5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlHelp.setBackground(new java.awt.Color(45, 118, 232));
        pnlHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHelpMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHelpMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHelpMouseEntered(evt);
            }
        });

        lblMenuName6.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        lblMenuName6.setForeground(new java.awt.Color(254, 254, 254));
        lblMenuName6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/help.png"))); // NOI18N
        lblMenuName6.setText("Help");
        lblMenuName6.setToolTipText("Need help...?");
        lblMenuName6.setIconTextGap(10);
        lblMenuName6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMenuName6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuName6MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlHelpLayout = new javax.swing.GroupLayout(pnlHelp);
        pnlHelp.setLayout(pnlHelpLayout);
        pnlHelpLayout.setHorizontalGroup(
            pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHelpLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblMenuName6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHelpLayout.setVerticalGroup(
            pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHelpLayout.createSequentialGroup()
                .addComponent(lblMenuName6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlInfo.setBackground(new java.awt.Color(45, 118, 232));
        pnlInfo.setToolTipText("");
        pnlInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlInfoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlInfoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlInfoMouseEntered(evt);
            }
        });

        lblMenuName7.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        lblMenuName7.setForeground(new java.awt.Color(254, 254, 254));
        lblMenuName7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/about_us.png"))); // NOI18N
        lblMenuName7.setText("Info");
        lblMenuName7.setToolTipText("Information about developers");
        lblMenuName7.setIconTextGap(10);
        lblMenuName7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMenuName7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuName7MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblMenuName7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addComponent(lblMenuName7)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlLogout.setBackground(new java.awt.Color(45, 118, 232));
        pnlLogout.setToolTipText("Click here to Logout");
        pnlLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLogoutMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLogoutMouseEntered(evt);
            }
        });

        lblMenuName8.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        lblMenuName8.setForeground(new java.awt.Color(254, 254, 254));
        lblMenuName8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/quit.png"))); // NOI18N
        lblMenuName8.setText("Log Out");
        lblMenuName8.setToolTipText("Click here to Logout");
        lblMenuName8.setIconTextGap(12);

        javax.swing.GroupLayout pnlLogoutLayout = new javax.swing.GroupLayout(pnlLogout);
        pnlLogout.setLayout(pnlLogoutLayout);
        pnlLogoutLayout.setHorizontalGroup(
            pnlLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoutLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblMenuName8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLogoutLayout.setVerticalGroup(
            pnlLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoutLayout.createSequentialGroup()
                .addComponent(lblMenuName8)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSideMenuLayout = new javax.swing.GroupLayout(pnlSideMenu);
        pnlSideMenu.setLayout(pnlSideMenuLayout);
        pnlSideMenuLayout.setHorizontalGroup(
            pnlSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideMenuLayout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
            .addComponent(pnlHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlHelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSideMenuLayout.setVerticalGroup(
            pnlSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pnlTop.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlHead.setBackground(new java.awt.Color(247, 247, 250));

        lblHeadText.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        lblHeadText.setText("Admin Panel");

        pnlUser.setBackground(new java.awt.Color(247, 247, 250));
        pnlUser.setToolTipText("Profile\n");
        pnlUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlUserMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlUserMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlUserMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlUserMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlUserMouseEntered(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("FULL NAME");
        lblUsername.setToolTipText("Profile\n");
        lblUsername.setAutoscrolls(true);
        lblUsername.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblUsername.setIconTextGap(0);
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsernameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsernameMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsernameMouseEntered(evt);
            }
        });

        lbluserimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbluserimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user2.png"))); // NOI18N
        lbluserimg.setToolTipText("Profile\n");
        lbluserimg.setAutoscrolls(true);
        lbluserimg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbluserimg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbluserimgMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbluserimgMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbluserimgMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbluserimg, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbluserimg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblHeadText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(pnlUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lblHeadText)
                .addGap(31, 31, 31))
            .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlParent.setBackground(new java.awt.Color(254, 254, 254));
        pnlParent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlParent, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUserMouseEntered
        pnlUser.setBackground(new Color(45,118,232));
        lblUsername.setForeground(Color.white);
        lbluserimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userWhite.png")));
       
    }//GEN-LAST:event_pnlUserMouseEntered

    private void pnlUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUserMouseExited
         pnlUser.setBackground(new Color(247,247,250)); 
         lblUsername.setForeground(Color.black);
        lbluserimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user2.png")));
    }//GEN-LAST:event_pnlUserMouseExited

    private void pnlUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUserMouseReleased
       // TODO add your handling code here:
    }//GEN-LAST:event_pnlUserMouseReleased

    private void pnlUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUserMouseClicked
           
            addUserDetailPage(); 
    }//GEN-LAST:event_pnlUserMouseClicked

    private void pnlUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUserMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlUserMousePressed

    private void pnlHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseEntered
            pnlHome.setBackground(new Color(17,80,204));
    }//GEN-LAST:event_pnlHomeMouseEntered

    private void pnlHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseExited
            pnlHome.setBackground(new Color(45,118,232));        // TODO add your handling code here:
    }//GEN-LAST:event_pnlHomeMouseExited

    private void pnlHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseClicked
                pnlHome.disable();
                    addHomePage();  // TODO add your handling code here:
                /*  setColor(pnlHome);
                  resetColor(pnlMenu);
                  resetColor(pnlHelp);
                  resetColor(pnlInfo);
                  resetColor(pnlLogout);
                  */
    }//GEN-LAST:event_pnlHomeMouseClicked

    private void pnlMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuMouseEntered
                pnlMenu.setBackground(new Color(17,80,204));// TODO add your handling code here:
    }//GEN-LAST:event_pnlMenuMouseEntered

    private void pnlMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuMouseClicked
                addMenuPage();// TODO add your handling code here:
                
                /*   setColor(pnlMenu);
                  resetColor(pnlHome);
                  resetColor(pnlHelp);
                  resetColor(pnlInfo);
                  resetColor(pnlLogout);*/
    }//GEN-LAST:event_pnlMenuMouseClicked

    private void pnlMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuMouseExited
             pnlMenu.setBackground(new Color(45,118,232));// TODO add your handling code here:
    }//GEN-LAST:event_pnlMenuMouseExited

    private void pnlHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHelpMouseClicked
                setColor(pnlHelp);
                  resetColor(pnlMenu);
                  resetColor(pnlHome);
                  resetColor(pnlInfo);
                  resetColor(pnlLogout);
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlHelpMouseClicked

    private void pnlHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHelpMouseEntered
        pnlHelp.setBackground(new Color(17,80,204));// TODO add your handling code here:
    }//GEN-LAST:event_pnlHelpMouseEntered

    private void pnlHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHelpMouseExited
       pnlHelp.setBackground(new Color(45,118,232)); // TODO add your handling code here:
    }//GEN-LAST:event_pnlHelpMouseExited

    private void pnlInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInfoMouseClicked
        setColor(pnlInfo);
                  resetColor(pnlMenu);
                  resetColor(pnlHelp);
                  resetColor(pnlHome);
                  resetColor(pnlLogout);// TODO add your handling code here:
    }//GEN-LAST:event_pnlInfoMouseClicked

    private void pnlInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInfoMouseEntered
         pnlInfo.setBackground(new Color(17,80,204));// TODO add your handling code here:
    }//GEN-LAST:event_pnlInfoMouseEntered

    private void pnlInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInfoMouseExited
       pnlInfo.setBackground(new Color(45,118,232));// TODO add your handling code here:
    }//GEN-LAST:event_pnlInfoMouseExited

    private void pnlLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoutMouseClicked
            setColor(pnlLogout);
                  resetColor(pnlMenu);
                  resetColor(pnlHelp);
                  resetColor(pnlInfo);
                  resetColor(pnlHome);// TODO add your handling code here:
    }//GEN-LAST:event_pnlLogoutMouseClicked

    private void pnlLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoutMouseEntered
        pnlLogout.setBackground(new Color(17,80,204));// TODO add your handling code here:
    }//GEN-LAST:event_pnlLogoutMouseEntered

    private void pnlLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogoutMouseExited
         pnlLogout.setBackground(new Color(45,118,232));// TODO add your handling code here:
    }//GEN-LAST:event_pnlLogoutMouseExited

    private void lblMenuName3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuName3MouseClicked
        pnlHome.disable();
        addHomePage();        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuName3MouseClicked

    private void lblMenuName3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuName3MouseEntered
        pnlHome.setBackground(new Color(17,80,204));        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuName3MouseEntered

    private void lblMenuName3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuName3MouseExited
        pnlHome.setBackground(new Color(45,118,232));            // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuName3MouseExited

    private void lblMenuName5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuName5MouseClicked
        addMenuPage();        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuName5MouseClicked

    private void lblMenuName5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuName5MouseEntered
        pnlMenu.setBackground(new Color(17,80,204));        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuName5MouseEntered

    private void lblMenuName5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuName5MouseExited
        pnlMenu.setBackground(new Color(45,118,232));        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuName5MouseExited

    private void lblMenuName6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuName6MouseEntered
        pnlHelp.setBackground(new Color(17,80,204));        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuName6MouseEntered

    private void lblMenuName6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuName6MouseExited
        pnlHelp.setBackground(new Color(45,118,232));        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuName6MouseExited

    private void lblMenuName7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuName7MouseEntered
        pnlInfo.setBackground(new Color(17,80,204));        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuName7MouseEntered

    private void lblMenuName7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuName7MouseExited
        pnlInfo.setBackground(new Color(45,118,232));        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuName7MouseExited

    private void lbluserimgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbluserimgMouseClicked
        addUserDetailPage();         // TODO add your handling code here:
    }//GEN-LAST:event_lbluserimgMouseClicked

    private void lblUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseClicked
        addUserDetailPage();         // TODO add your handling code here:
    }//GEN-LAST:event_lblUsernameMouseClicked

    private void lbluserimgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbluserimgMouseEntered
        pnlUser.setBackground(new Color(45,118,232));
        lblUsername.setForeground(Color.white);
        lbluserimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userWhite.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_lbluserimgMouseEntered

    private void lblUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseEntered
        pnlUser.setBackground(new Color(45,118,232));
        lblUsername.setForeground(Color.white);
        lbluserimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userWhite.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsernameMouseEntered

    private void lbluserimgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbluserimgMouseExited
        pnlUser.setBackground(new Color(247,247,250)); 
         lblUsername.setForeground(Color.black);
        lbluserimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user2.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_lbluserimgMouseExited

    private void lblUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseExited
        pnlUser.setBackground(new Color(247,247,250)); 
         lblUsername.setForeground(Color.black);
        lbluserimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user2.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsernameMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               dashboard= new Dashboard("XYZ","admin","Admin Panel");
               dashboard.setProfileName();
                try {
                    dashboard.addPanels(dashboard);
                } catch (SQLException ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHeadText;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenuName3;
    private javax.swing.JLabel lblMenuName5;
    private javax.swing.JLabel lblMenuName6;
    private javax.swing.JLabel lblMenuName7;
    private javax.swing.JLabel lblMenuName8;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lbluserimg;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPanel pnlHelp;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlLogout;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlParent;
    private javax.swing.JPanel pnlSideMenu;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnlUser;
    // End of variables declaration//GEN-END:variables
}
