/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author thakur-huni
 */
public class Login extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Login
     */
    private BusMethodInterface busLogic;
    private ResultSet rs;
    private String name,usertype,username;
    private boolean correctSts=false;
    private Thread thread;
    public Login() {
        
        initComponents();
        thread=null;
        setVisible(true);
        busLogic=new BusinessLogic();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iconBook = new javax.swing.JLabel();
        lblLoginLogo = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblUsername1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnCancel = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        pnlLeft.setBackground(new java.awt.Color(45, 118, 232));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/e-lib.jpeg"))); // NOI18N
        pnlLeft.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        pnlRight.setBackground(new java.awt.Color(254, 254, 254));

        iconBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/books.png"))); // NOI18N

        lblLoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.jpeg"))); // NOI18N

        lblUsername.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        lblUsername.setText("Username");

        txtUsername.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N

        lblUsername1.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        lblUsername1.setText("Password");

        txtPassword.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N

        btnCancel.setBackground(new java.awt.Color(45, 118, 232));
        btnCancel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(254, 254, 254));
        btnCancel.setText("Cancel");
        btnCancel.setBorderPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(45, 118, 232));
        btnLogin.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(254, 254, 254));
        btnLogin.setText("Login");
        btnLogin.setBorderPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRightLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(iconBook))
                    .addGroup(pnlRightLayout.createSequentialGroup()
                        .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRightLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1))
                            .addGroup(pnlRightLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lblLoginLogo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUsername)
                    .addComponent(lblUsername1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRightLayout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPassword)
                    .addComponent(txtUsername))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsername1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconBook)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      if(JOptionPane.showConfirmDialog(this, "Do you really want to exit ?","Select an Option",1)==0)
      {
           dispose();
            System.exit(0); 
      }
           // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
       if(isFieldFilled()==true)
       {
           validateUser();
       }
    }//GEN-LAST:event_btnLoginActionPerformed
    
    boolean isFieldFilled()
    {
        try
        {
            correctSts=true;
            if(txtUsername.getText().length()<=0)
            {
                correctSts=false;
                JOptionPane.showMessageDialog(this,"Please enter your username.");
                txtUsername.grabFocus();
                throw new MyExpection("");
            }
            if(txtPassword.getText().length()<=0)
            {
                correctSts=false;
                JOptionPane.showMessageDialog(this, "Please enter your password.");
                txtPassword.grabFocus();
                throw new MyExpection("");
            }
        }
        catch(MyExpection e)
        {
            
        }
        return correctSts;
    }
    
    void validateUser()
    {
        if(thread==null)
        {
            thread=new Thread(this);
            thread.start();
        }
            
    }
    @Override
    public void run()
    {
        if(!thread.interrupted())
        {
            btnLogin.setText(null);
            btnLogin.setBackground(Color.white);
            btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/blackFastLoading.gif")));
                   try 
                   {
                   rs=busLogic.login(txtUsername.getText(), txtPassword.getText());
                   if(rs==null)
                   {
                       throw new MyExpection("");
                   }
                   if(rs.next())
                      {
                          name=rs.getString(2);
                          username=rs.getString(3);
                          usertype=rs.getString(5);
                      }
                      busLogic.disconnectNow();
                      btnLogin.setText("Login");
                     btnLogin.setBackground(new Color(45,118,232));
                     btnLogin.setIcon(null);
                     if(usertype!=null)
                     {
                          if(usertype.equals("Admin"))
                          {
                              JOptionPane.showMessageDialog(this, "Admin: Welcome "+name);
                              dispose();
                              Dashboard dashboard= new Dashboard(name,username,usertype);
                              dashboard.setProfileName();
                               dashboard.addPanels(dashboard);
                               name=null;
                              username=null;
                              usertype=null;
                          }
                            else if(usertype.equals("Student"))
                          {
                              JOptionPane.showMessageDialog(this, "Student: Welcome "+name);
                          }

                     }
                     else
                           {
                              JOptionPane.showMessageDialog(this, "Invalid Username/Password ");
                           }


               } catch (SQLException ex) {
                   Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
               }
               catch(MyExpection e)
               {
                  // JOptionPane.showMessageDialog(this, "Invalid Username / Password.");
               }
            
        }
        thread.interrupt();
        thread=null;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel iconBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLoginLogo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
