/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author thakur-huni
 */
public class Menus extends javax.swing.JPanel {

    /**
     * Creates new form Menus
     */
    Dashboard dashboard;
    public Menus(Dashboard dashboard) {
        initComponents();
        this.dashboard=dashboard;
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(40);
    }
    void panelMouseEnter(JPanel pnl,JLabel lblTxt,JLabel lblImg,String path)
    {
        pnl.setBackground(new Color(45,118,232));
        lblTxt.setForeground(Color.white);
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }
    void panelMouseExit(JPanel pnl,JLabel lblTxt,JLabel lblImg,String path)
    {
        pnl.setBackground(new Color(247,247,247));
        lblTxt.setForeground(Color.black);
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pnlAddUser = new javax.swing.JPanel();
        lblAddUserText = new javax.swing.JLabel();
        lblAddUserImg = new javax.swing.JLabel();
        pnlManageUser = new javax.swing.JPanel();
        lblManageUserText = new javax.swing.JLabel();
        lblManageUserImg = new javax.swing.JLabel();
        pnlManageAdmin = new javax.swing.JPanel();
        lblManageAdminText = new javax.swing.JLabel();
        lblManageAdminImg = new javax.swing.JLabel();
        pnlAddBook = new javax.swing.JPanel();
        lblAddBookText = new javax.swing.JLabel();
        lblAddBookImg = new javax.swing.JLabel();
        pnlAddGenre = new javax.swing.JPanel();
        lblAddGenreText = new javax.swing.JLabel();
        lblAddGenreImg = new javax.swing.JLabel();
        pnlManageBooks = new javax.swing.JPanel();
        lblManageBookText = new javax.swing.JLabel();
        lblManageBookImg = new javax.swing.JLabel();
        pnlIssueBook = new javax.swing.JPanel();
        lblIssueBookText = new javax.swing.JLabel();
        lblIssueBookImg = new javax.swing.JLabel();
        pnlReturnBook = new javax.swing.JPanel();
        lblReturnBookText = new javax.swing.JLabel();
        lblReturnBookImg = new javax.swing.JLabel();
        pnlViewIssuedBooks = new javax.swing.JPanel();
        lblIssuedBookText = new javax.swing.JLabel();
        lblIssuedBookImg = new javax.swing.JLabel();
        pnlBadUser = new javax.swing.JPanel();
        lblBadUserText = new javax.swing.JLabel();
        lblBadUserImg = new javax.swing.JLabel();
        pnlDefaulters = new javax.swing.JPanel();
        lblDefaultersText = new javax.swing.JLabel();
        lblDefaultersImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setForeground(new java.awt.Color(254, 254, 254));
        setPreferredSize(new java.awt.Dimension(615, 359));

        lblTitle.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        lblTitle.setText("Menu");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        pnlAddUser.setBackground(new java.awt.Color(248, 247, 247));
        pnlAddUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pnlAddUser.setToolTipText("Add User");
        pnlAddUser.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddUserMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAddUserMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAddUserMouseEntered(evt);
            }
        });

        lblAddUserText.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        lblAddUserText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddUserText.setText("Add User");
        lblAddUserText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAddUserImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddUserImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addUser_B.png"))); // NOI18N
        lblAddUserImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlAddUserLayout = new javax.swing.GroupLayout(pnlAddUser);
        pnlAddUser.setLayout(pnlAddUserLayout);
        pnlAddUserLayout.setHorizontalGroup(
            pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddUserImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblAddUserText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAddUserLayout.setVerticalGroup(
            pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAddUserImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddUserText)
                .addContainerGap())
        );

        pnlManageUser.setBackground(new java.awt.Color(248, 247, 247));
        pnlManageUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pnlManageUser.setPreferredSize(new java.awt.Dimension(186, 106));
        pnlManageUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlManageUserMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlManageUserMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlManageUserMouseEntered(evt);
            }
        });

        lblManageUserText.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        lblManageUserText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageUserText.setText("Manage Users");
        lblManageUserText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblManageUserText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageUserTextMouseClicked(evt);
            }
        });

        lblManageUserImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageUserImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/manageUser_B.png"))); // NOI18N
        lblManageUserImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblManageUserImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageUserImgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlManageUserLayout = new javax.swing.GroupLayout(pnlManageUser);
        pnlManageUser.setLayout(pnlManageUserLayout);
        pnlManageUserLayout.setHorizontalGroup(
            pnlManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblManageUserImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblManageUserText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        pnlManageUserLayout.setVerticalGroup(
            pnlManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageUserLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(lblManageUserImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblManageUserText)
                .addContainerGap())
        );

        pnlManageAdmin.setBackground(new java.awt.Color(248, 247, 247));
        pnlManageAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pnlManageAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlManageAdminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlManageAdminMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlManageAdminMouseEntered(evt);
            }
        });

        lblManageAdminText.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        lblManageAdminText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageAdminText.setText("Manage Admins");
        lblManageAdminText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblManageAdminImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageAdminImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/manageUser_B.png"))); // NOI18N
        lblManageAdminImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlManageAdminLayout = new javax.swing.GroupLayout(pnlManageAdmin);
        pnlManageAdmin.setLayout(pnlManageAdminLayout);
        pnlManageAdminLayout.setHorizontalGroup(
            pnlManageAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblManageAdminImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblManageAdminText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );
        pnlManageAdminLayout.setVerticalGroup(
            pnlManageAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblManageAdminImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblManageAdminText)
                .addContainerGap())
        );

        pnlAddBook.setBackground(new java.awt.Color(248, 247, 247));
        pnlAddBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pnlAddBook.setToolTipText("Add User");
        pnlAddBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddBookMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAddBookMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAddBookMouseEntered(evt);
            }
        });

        lblAddBookText.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        lblAddBookText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddBookText.setText("Add Book");
        lblAddBookText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAddBookImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddBookImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addBook_B.png"))); // NOI18N
        lblAddBookImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlAddBookLayout = new javax.swing.GroupLayout(pnlAddBook);
        pnlAddBook.setLayout(pnlAddBookLayout);
        pnlAddBookLayout.setHorizontalGroup(
            pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddBookText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblAddBookImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAddBookLayout.setVerticalGroup(
            pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddBookLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAddBookImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddBookText)
                .addContainerGap())
        );

        pnlAddGenre.setBackground(new java.awt.Color(248, 247, 247));
        pnlAddGenre.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pnlAddGenre.setPreferredSize(new java.awt.Dimension(186, 106));
        pnlAddGenre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddGenreMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAddGenreMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAddGenreMouseEntered(evt);
            }
        });

        lblAddGenreText.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        lblAddGenreText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddGenreText.setText("Add Genre");
        lblAddGenreText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAddGenreImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddGenreImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addGenre_B.png"))); // NOI18N
        lblAddGenreImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlAddGenreLayout = new javax.swing.GroupLayout(pnlAddGenre);
        pnlAddGenre.setLayout(pnlAddGenreLayout);
        pnlAddGenreLayout.setHorizontalGroup(
            pnlAddGenreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddGenreImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblAddGenreText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAddGenreLayout.setVerticalGroup(
            pnlAddGenreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddGenreLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(lblAddGenreImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddGenreText)
                .addContainerGap())
        );

        pnlManageBooks.setBackground(new java.awt.Color(248, 247, 247));
        pnlManageBooks.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pnlManageBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlManageBooksMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlManageBooksMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlManageBooksMouseEntered(evt);
            }
        });

        lblManageBookText.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        lblManageBookText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageBookText.setText("Manage Books");
        lblManageBookText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblManageBookImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageBookImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/manageBook_B.png"))); // NOI18N
        lblManageBookImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlManageBooksLayout = new javax.swing.GroupLayout(pnlManageBooks);
        pnlManageBooks.setLayout(pnlManageBooksLayout);
        pnlManageBooksLayout.setHorizontalGroup(
            pnlManageBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblManageBookImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblManageBookText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlManageBooksLayout.setVerticalGroup(
            pnlManageBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageBooksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblManageBookImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblManageBookText)
                .addContainerGap())
        );

        pnlIssueBook.setBackground(new java.awt.Color(248, 247, 247));
        pnlIssueBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pnlIssueBook.setToolTipText("Click here to issue a book");
        pnlIssueBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlIssueBookMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlIssueBookMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlIssueBookMouseEntered(evt);
            }
        });

        lblIssueBookText.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        lblIssueBookText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIssueBookText.setText("Issue Book");
        lblIssueBookText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblIssueBookImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIssueBookImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/issueBook_B.png"))); // NOI18N
        lblIssueBookImg.setToolTipText("");
        lblIssueBookImg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblIssueBookImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlIssueBookLayout = new javax.swing.GroupLayout(pnlIssueBook);
        pnlIssueBook.setLayout(pnlIssueBookLayout);
        pnlIssueBookLayout.setHorizontalGroup(
            pnlIssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIssueBookImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIssueBookText, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        pnlIssueBookLayout.setVerticalGroup(
            pnlIssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIssueBookLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(lblIssueBookImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIssueBookText)
                .addContainerGap())
        );

        pnlReturnBook.setBackground(new java.awt.Color(248, 247, 247));
        pnlReturnBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pnlReturnBook.setPreferredSize(new java.awt.Dimension(186, 106));
        pnlReturnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReturnBookMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReturnBookMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReturnBookMouseEntered(evt);
            }
        });

        lblReturnBookText.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        lblReturnBookText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReturnBookText.setText("Return Book");
        lblReturnBookText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblReturnBookImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReturnBookImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/returnBook_B.png"))); // NOI18N
        lblReturnBookImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlReturnBookLayout = new javax.swing.GroupLayout(pnlReturnBook);
        pnlReturnBook.setLayout(pnlReturnBookLayout);
        pnlReturnBookLayout.setHorizontalGroup(
            pnlReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReturnBookImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblReturnBookText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlReturnBookLayout.setVerticalGroup(
            pnlReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReturnBookLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblReturnBookImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReturnBookText)
                .addContainerGap())
        );

        pnlViewIssuedBooks.setBackground(new java.awt.Color(248, 247, 247));
        pnlViewIssuedBooks.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pnlViewIssuedBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlViewIssuedBooksMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlViewIssuedBooksMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlViewIssuedBooksMouseEntered(evt);
            }
        });

        lblIssuedBookText.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        lblIssuedBookText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIssuedBookText.setText("Issued Books");
        lblIssuedBookText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblIssuedBookImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIssuedBookImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/issuedBook_B.png"))); // NOI18N
        lblIssuedBookImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlViewIssuedBooksLayout = new javax.swing.GroupLayout(pnlViewIssuedBooks);
        pnlViewIssuedBooks.setLayout(pnlViewIssuedBooksLayout);
        pnlViewIssuedBooksLayout.setHorizontalGroup(
            pnlViewIssuedBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIssuedBookImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIssuedBookText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlViewIssuedBooksLayout.setVerticalGroup(
            pnlViewIssuedBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewIssuedBooksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIssuedBookImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIssuedBookText)
                .addContainerGap())
        );

        pnlBadUser.setBackground(new java.awt.Color(248, 247, 247));
        pnlBadUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pnlBadUser.setToolTipText("Add User");
        pnlBadUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBadUserMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBadUserMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBadUserMouseEntered(evt);
            }
        });

        lblBadUserText.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        lblBadUserText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadUserText.setText("Bad Users");
        lblBadUserText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblBadUserImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadUserImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/badUser_B.png"))); // NOI18N
        lblBadUserImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlBadUserLayout = new javax.swing.GroupLayout(pnlBadUser);
        pnlBadUser.setLayout(pnlBadUserLayout);
        pnlBadUserLayout.setHorizontalGroup(
            pnlBadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBadUserImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblBadUserText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBadUserLayout.setVerticalGroup(
            pnlBadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBadUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBadUserImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBadUserText)
                .addContainerGap())
        );

        pnlDefaulters.setBackground(new java.awt.Color(248, 247, 247));
        pnlDefaulters.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pnlDefaulters.setPreferredSize(new java.awt.Dimension(186, 106));
        pnlDefaulters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDefaultersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDefaultersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDefaultersMouseEntered(evt);
            }
        });

        lblDefaultersText.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        lblDefaultersText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDefaultersText.setText("Defaulters");
        lblDefaultersText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDefaultersImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDefaultersImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/defaulter_B.png"))); // NOI18N
        lblDefaultersImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlDefaultersLayout = new javax.swing.GroupLayout(pnlDefaulters);
        pnlDefaulters.setLayout(pnlDefaultersLayout);
        pnlDefaultersLayout.setHorizontalGroup(
            pnlDefaultersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDefaultersText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDefaultersImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDefaultersLayout.setVerticalGroup(
            pnlDefaultersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDefaultersLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(lblDefaultersImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDefaultersText)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlIssueBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAddBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBadUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlReturnBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAddGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlManageUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDefaulters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlManageAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlManageBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlViewIssuedBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlReturnBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlViewIssuedBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlIssueBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlManageUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlManageAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAddGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAddBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlManageBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDefaulters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBadUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlAddUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddUserMouseEntered
            panelMouseEnter(pnlAddUser, lblAddUserText,lblAddUserImg,"/Icons/addUser_W.png");
    }//GEN-LAST:event_pnlAddUserMouseEntered

    private void pnlAddUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddUserMouseExited
            panelMouseExit(pnlAddUser, lblAddUserText,lblAddUserImg,"/Icons/addUser_B.png");
// TODO add your handling code here:
    }//GEN-LAST:event_pnlAddUserMouseExited

    private void pnlAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddUserMouseClicked
            dashboard.addNewUserPage(); // TODO add your handling code here:
    }//GEN-LAST:event_pnlAddUserMouseClicked

    private void pnlManageUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlManageUserMouseClicked
            dashboard.addManageUserPage();        // TODO add your handling code here:
    }//GEN-LAST:event_pnlManageUserMouseClicked

    private void pnlManageUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlManageUserMouseExited
        // TODO add your handling code here:
         panelMouseExit(pnlManageUser, lblManageUserText,lblManageUserImg,"/Icons/manageUser_B.png");
    }//GEN-LAST:event_pnlManageUserMouseExited

    private void pnlManageUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlManageUserMouseEntered
            panelMouseEnter(pnlManageUser, lblManageUserText,lblManageUserImg,"/Icons/manageUser_W.png");
                   // TODO add your handling code here:
    }//GEN-LAST:event_pnlManageUserMouseEntered

    private void pnlManageAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlManageAdminMouseClicked
            dashboard.addManageAdminPage();        // TODO add your handling code here:
    }//GEN-LAST:event_pnlManageAdminMouseClicked

    private void pnlManageAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlManageAdminMouseExited
            panelMouseExit(pnlManageAdmin, lblManageAdminText,lblManageAdminImg,"/Icons/manageUser_B.png");
    }//GEN-LAST:event_pnlManageAdminMouseExited

    private void pnlManageAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlManageAdminMouseEntered
            panelMouseEnter(pnlManageAdmin, lblManageAdminText,lblManageAdminImg,"/Icons/manageUser_W.png");
    }//GEN-LAST:event_pnlManageAdminMouseEntered
    
    private void pnlAddBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddBookMouseClicked
                dashboard.addBookAddPage();        // TODO add your handling code here:
    }//GEN-LAST:event_pnlAddBookMouseClicked

    private void pnlAddBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddBookMouseExited
        panelMouseExit(pnlAddBook, lblAddBookText,lblAddBookImg,"/Icons/addBook_B.png");
    }//GEN-LAST:event_pnlAddBookMouseExited

    private void pnlAddBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddBookMouseEntered
        panelMouseEnter(pnlAddBook, lblAddBookText,lblAddBookImg,"/Icons/addBook_W.png");
    }//GEN-LAST:event_pnlAddBookMouseEntered

    private void pnlAddGenreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddGenreMouseClicked
            dashboard.addBookCatAddPage();        // TODO add your handling code here:
    }//GEN-LAST:event_pnlAddGenreMouseClicked

    private void pnlAddGenreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddGenreMouseExited
        panelMouseExit(pnlAddGenre, lblAddGenreText,lblAddGenreImg,"/Icons/addGenre_B.png");
    }//GEN-LAST:event_pnlAddGenreMouseExited

    private void pnlAddGenreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddGenreMouseEntered
        panelMouseEnter(pnlAddGenre, lblAddGenreText,lblAddGenreImg,"/Icons/addGenre_W.png");
    }//GEN-LAST:event_pnlAddGenreMouseEntered

    private void pnlManageBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlManageBooksMouseClicked
            dashboard.addManageBookPage();        // TODO add your handling code here:
    }//GEN-LAST:event_pnlManageBooksMouseClicked

    private void pnlManageBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlManageBooksMouseExited
       panelMouseExit(pnlManageBooks, lblManageBookText,lblManageBookImg,"/Icons/manageBook_B.png");
    }//GEN-LAST:event_pnlManageBooksMouseExited

    private void pnlManageBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlManageBooksMouseEntered
        panelMouseEnter(pnlManageBooks, lblManageBookText,lblManageBookImg,"/Icons/manageBook_W.png");
    }//GEN-LAST:event_pnlManageBooksMouseEntered

    private void pnlIssueBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlIssueBookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlIssueBookMouseClicked

    private void pnlIssueBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlIssueBookMouseExited
        panelMouseExit(pnlIssueBook, lblIssueBookText,lblIssueBookImg,"/Icons/issueBook_B.png");
    }//GEN-LAST:event_pnlIssueBookMouseExited

    private void pnlIssueBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlIssueBookMouseEntered
       panelMouseEnter(pnlIssueBook, lblIssueBookText,lblIssueBookImg,"/Icons/issueBook_W.png");
    }//GEN-LAST:event_pnlIssueBookMouseEntered

    private void pnlReturnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnBookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlReturnBookMouseClicked

    private void pnlReturnBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnBookMouseExited
        panelMouseExit(pnlReturnBook, lblReturnBookText,lblReturnBookImg,"/Icons/returnBook_B.png");
    }//GEN-LAST:event_pnlReturnBookMouseExited

    private void pnlReturnBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnBookMouseEntered
        panelMouseEnter(pnlReturnBook, lblReturnBookText,lblReturnBookImg,"/Icons/returnBook_W.png");
    }//GEN-LAST:event_pnlReturnBookMouseEntered

    private void pnlViewIssuedBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewIssuedBooksMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlViewIssuedBooksMouseClicked

    private void pnlViewIssuedBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewIssuedBooksMouseExited
        panelMouseExit(pnlViewIssuedBooks, lblIssuedBookText,lblIssuedBookImg,"/Icons/issuedBook_B.png");
    }//GEN-LAST:event_pnlViewIssuedBooksMouseExited

    private void pnlViewIssuedBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewIssuedBooksMouseEntered
        panelMouseEnter(pnlViewIssuedBooks, lblIssuedBookText,lblIssuedBookImg,"/Icons/issuedBook_W.png");
    }//GEN-LAST:event_pnlViewIssuedBooksMouseEntered

    private void pnlBadUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBadUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlBadUserMouseClicked

    private void pnlBadUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBadUserMouseExited
        panelMouseExit(pnlBadUser, lblBadUserText,lblBadUserImg,"/Icons/badUser_B.png");
    }//GEN-LAST:event_pnlBadUserMouseExited

    private void pnlBadUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBadUserMouseEntered
        panelMouseEnter(pnlBadUser, lblBadUserText,lblBadUserImg,"/Icons/badUser_W.png");
    }//GEN-LAST:event_pnlBadUserMouseEntered

    private void pnlDefaultersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDefaultersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDefaultersMouseClicked

    private void pnlDefaultersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDefaultersMouseExited
        panelMouseExit(pnlDefaulters, lblDefaultersText,lblDefaultersImg,"/Icons/defaulter_B.png");
    }//GEN-LAST:event_pnlDefaultersMouseExited

    private void pnlDefaultersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDefaultersMouseEntered
                panelMouseEnter(pnlDefaulters, lblDefaultersText,lblDefaultersImg,"/Icons/defaulter_W.png");
    }//GEN-LAST:event_pnlDefaultersMouseEntered

    private void lblManageUserImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageUserImgMouseClicked
dashboard.addManageUserPage();         // TODO add your handling code here:
    }//GEN-LAST:event_lblManageUserImgMouseClicked

    private void lblManageUserTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageUserTextMouseClicked
dashboard.addManageUserPage();         // TODO add your handling code here:
    }//GEN-LAST:event_lblManageUserTextMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddBookImg;
    private javax.swing.JLabel lblAddBookText;
    private javax.swing.JLabel lblAddGenreImg;
    private javax.swing.JLabel lblAddGenreText;
    private javax.swing.JLabel lblAddUserImg;
    private javax.swing.JLabel lblAddUserText;
    private javax.swing.JLabel lblBadUserImg;
    private javax.swing.JLabel lblBadUserText;
    private javax.swing.JLabel lblDefaultersImg;
    private javax.swing.JLabel lblDefaultersText;
    private javax.swing.JLabel lblIssueBookImg;
    private javax.swing.JLabel lblIssueBookText;
    private javax.swing.JLabel lblIssuedBookImg;
    private javax.swing.JLabel lblIssuedBookText;
    private javax.swing.JLabel lblManageAdminImg;
    private javax.swing.JLabel lblManageAdminText;
    private javax.swing.JLabel lblManageBookImg;
    private javax.swing.JLabel lblManageBookText;
    private javax.swing.JLabel lblManageUserImg;
    private javax.swing.JLabel lblManageUserText;
    private javax.swing.JLabel lblReturnBookImg;
    private javax.swing.JLabel lblReturnBookText;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlAddBook;
    private javax.swing.JPanel pnlAddGenre;
    private javax.swing.JPanel pnlAddUser;
    private javax.swing.JPanel pnlBadUser;
    private javax.swing.JPanel pnlDefaulters;
    private javax.swing.JPanel pnlIssueBook;
    private javax.swing.JPanel pnlManageAdmin;
    private javax.swing.JPanel pnlManageBooks;
    private javax.swing.JPanel pnlManageUser;
    private javax.swing.JPanel pnlReturnBook;
    private javax.swing.JPanel pnlViewIssuedBooks;
    // End of variables declaration//GEN-END:variables
}
